Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.define "master" do |kube|
    kube.vm.hostname = "master.myelkdomain.com"
	#config.ssh.username = 'root'
	#config.ssh.password = 'vagrant'
	#config.ssh.insert_key = 'true'
    kube.vm.network "private_network", ip: "192.168.0.20"
    config.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "4048"]
       vb.customize ["modifyvm", :id, "--cpus", "1"]
    end  
    kube.vm.provision "shell", inline: $script
  end
 



 config.vm.define "node-01" do |kube|
    kube.vm.hostname = "node-01.myelkdomain.com"
	#config.ssh.username = 'root'
	#config.ssh.password = 'vagrant'
	#config.ssh.insert_key = 'true'
    kube.vm.network "private_network", ip: "192.168.0.21"
    config.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
    kube.vm.provision "shell", inline: $script
  end

 config.vm.define "node-02" do |kube|
    kube.vm.hostname = "node-02.myelkdomain.com"
	#config.ssh.username = 'root'
	#config.ssh.password = 'vagrant'
	#config.ssh.insert_key = 'true'
    kube.vm.network "private_network", ip: "192.168.0.22"
    config.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
    kube.vm.provision "shell", inline: $script
  end
  
 config.vm.define "node-03" do |kube|
    kube.vm.hostname = "node-03.myelkdomain.com"
	#config.ssh.username = 'root'
	#config.ssh.password = 'vagrant'
	#config.ssh.insert_key = 'true'
    kube.vm.network "private_network", ip: "192.168.0.23"
    config.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
    kube.vm.provision "shell", inline: $script
  end

  
$script = <<SCRIPT
echo I am provisioning...
echo "r00tme" | sudo passwd --stdin  root
echo "###########Setting Elastic Search Parameters###############"
sudo su -
yum install -y vim net-tools java-1.8.0-openjdk
echo "elastic - nofile 65536" >>  /etc/security/limits.conf
echo  "vm.max_map_count=262144" >> /etc/sysctl.conf
sysctl -p
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd.service
echo "###########Downloading TARS###############"
sudo cp /vagrant/hosts /etc/hosts
sudo useradd elastic
echo "elastic" | sudo passwd --stdin elastic
sudo su - elastic
cd /home/elastic/
curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.0.tar.gz
curl -O https://artifacts.elastic.co/downloads/kibana/kibana-6.5.0-linux-x86_64.tar.gz

tar xfvz elasticsearch-6.5.0.tar.gz
tar xfz kibana-6.5.0-linux-x86_64.tar.gz

sudo chown elastic:elastic -R /home/elastic/elasticsearch-*
sudo chown elastic:elastic -R /home/elastic/kibana-*






sudo swapoff -a

SCRIPT

end
